FinalProject/Controllers/BusinessesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EX5.Models;
using FinalProject.Dal;

namespace EX5.Controllers
{
    public class BusinessesController : Controller
    {
        private GeneralDbContext db = new GeneralDbContext();

        [Authorize]
        public ActionResult Admin()
        {
            return View(db.DBBusiness.ToList());
        }

        [Authorize]
        // GET: Businesses
        public ActionResult Index(string BusinessName, string Category, string StreetAddress, string City)
        {
            var Bussinesses1 = (from s in db.DBBusiness select s).ToList();

            var Bussinesses = from s in Bussinesses1
                              select new Business()
                              {
                                  BusinessID = s.BusinessID,
                                  BusinessName = s.BusinessName,
                                  Owner = s.Owner,
                                  PhoneNumber = s.PhoneNumber,
                                  StreetAddress = s.StreetAddress,
                                  City = s.City,
                                  Website = s.Website,
                                  Description = s.Description,
                                  AVGrank = s.AVGrank,
                                  CategoryID = s.CategoryID,
                                  Category = db.DBCategories.Where(x => x.CategoryID == s.CategoryID).FirstOrDefault()
                              };
            if (!String.IsNullOrEmpty(BusinessName))
            {
                Bussinesses = Bussinesses.Where(s => s.BusinessName.ToLower().Contains(BusinessName.ToLower()));
            }
            if (!String.IsNullOrEmpty(Category))
            {
                Bussinesses = Bussinesses.Where(s => s.Category.CategoryName.ToLower().Contains(Category.ToLower()));
            }
            if (!String.IsNullOrEmpty(StreetAddress))
            {
                Bussinesses = Bussinesses.Where(s => s.StreetAddress.ToLower().Contains(StreetAddress.ToLower()));
            }
            if (!String.IsNullOrEmpty(City))
            {
                Bussinesses = Bussinesses.Where(s => s.City.ToLower().Contains(City.ToLower()));
            }
            return View(Bussinesses);
        }

        [Authorize]
        // GET: Businesses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Business business = db.DBBusiness.Find(id);
            if (business == null)
            {
                return HttpNotFound();
            }
            return View(business);
        }

        [Authorize]
        // GET: Businesses/Create
        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.DBCategories.ToList(), "CategoryID", "CategoryName");
            return View();
        }

        [Authorize]
        // POST: Businesses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,BusinessName,CategoryID,Type,Owner,PhoneNumber,Address,Website,Description,StreetAddress,City,AVGrank")] Business business)
        {
            if (ModelState.IsValid)
            {
                db.DBBusiness.Add(business);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryID = new SelectList(db.DBCategories.ToList(), "CategoryID", "CategoryName",business.CategoryID);
            return View(business);
        }

        [Authorize]
        // GET: Businesses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Business business = db.DBBusiness.Find(id);
            if (business == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryID = new SelectList(db.DBCategories.ToList(), "CategoryID", "CategoryName",business.CategoryID);
            return View(business);
        }

        [Authorize]
        // POST: Businesses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BusinessID,CategoryID,BusinessName,Type,Owner,PhoneNumber,StreetAddress,City,Website,Description,AVGrank,Photo,Video")] Business business)
        {
            if (ModelState.IsValid)
            {
                db.Entry(business).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryID = new SelectList(db.DBCategories.ToList(), "CategoryID", "CategoryName", business.CategoryID);
            return View(business);
        }

        [Authorize]
        // GET: Businesses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Business business = db.DBBusiness.Find(id);
            //var Bussinesses1 = db.DBBusiness.Find(id);
            if (business == null)
            {
                return HttpNotFound();
            }
            business.Category=db.DBCategories.Find(business.CategoryID);
            return View(business);
        }

        [Authorize]
        // POST: Businesses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Business business = db.DBBusiness.Find(id);
            db.DBBusiness.Remove(business);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpPost]
        public ActionResult GiveRank(int id, int rank)
        {
            Business business = db.DBBusiness.Find(id);
            int size = db.DBBusiness.Count();
            double newRank = (size * business.AVGrank + rank) / (size + 1);
            business.AVGrank = Convert.ToDouble(String.Format("{0:0.0}", newRank));
            db.SaveChanges();
            return Json(new { AVGrank = business.AVGrank });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }


}

FinalProject/Controllers/HomeController.cs
using FinalProject.Dal;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EX5.Controllers
{
    public class HomeController : Controller
    {
        private GeneralDbContext db = new GeneralDbContext();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact(string Street, string city, string manager)
        {
            var Offices = from o in db.DBOffice select o;
            if (!String.IsNullOrEmpty(Street))
            {
                Offices = Offices.Where(s => s.Street.ToLower().Contains(Street.ToLower()));
            }
            if (!String.IsNullOrEmpty(city))
            {
                Offices = Offices.Where(s => s.City.ToLower().Contains(city.ToLower()));
            }
            if (!String.IsNullOrEmpty(manager))
            {
                Offices = Offices.Where(s => s.Manager.ToLower().Contains(manager.ToLower()));
            }

            return View(Offices);
        }
    }
}

FinalProject/Controllers/OfficesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FinalProject.Dal;
using FinalProject.Models;
using System.Data.SqlClient;
using System.Configuration;

namespace FinalProject.Controllers
{
    public class OfficesController : Controller
    {
        private GeneralDbContext db = new GeneralDbContext();

        // GET: Offices
        public ActionResult Index(string Street, string city, string manager)
        {
            var Offices = from o in db.DBOffice select o;
            if (!String.IsNullOrEmpty(Street))
            {
                Offices = Offices.Where(s => s.Street.ToLower().Contains(Street.ToLower()));
            }
            if (!String.IsNullOrEmpty(city))
            {
                Offices = Offices.Where(s => s.City.ToLower().Contains(city.ToLower()));
            }
            if (!String.IsNullOrEmpty(manager))
            {
                Offices = Offices.Where(s => s.Manager.ToLower().Contains(manager.ToLower()));
            }

            return View(Offices);
        }

        // GET: Offices/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Office office = db.DBOffice.Find(id);
            if (office == null)
            {
                return HttpNotFound();
            }
            return View(office);
        }

        // GET: Offices/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Offices/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OfficeID,BusinessName,City,Street,HouseNumber,Latitude,Longitude,Owner,Manager")] Office office)
        {
            if (ModelState.IsValid)
            {
                db.DBOffice.Add(office);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(office);
        }

        // GET: Offices/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Office office = db.DBOffice.Find(id);
            if (office == null)
            {
                return HttpNotFound();
            }
            return View(office);
        }

        // POST: Offices/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OfficeID,BusinessName,City,Street,HouseNumber,Latitude,Longitude,Owner,Manager")] Office office)
        {
            if (ModelState.IsValid)
            {
                db.Entry(office).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(office);
        }

        // GET: Offices/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Office office = db.DBOffice.Find(id);
            if (office == null)
            {
                return HttpNotFound();
            }
            return View(office);
        }

        // POST: Offices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Office office = db.DBOffice.Find(id);
            db.DBOffice.Remove(office);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FinalProject/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>Contact Infornation</h3>

<address>
    22 Migdal David Street<br />
    Rehovot, Israel  98052<br />
    03-9522248
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@MyBiz.com">Support@MyBiz.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@MyBiz.com">Marketing@MyBiz.com</a>
</address>


<script type="text/javascript">

    var img = new Image();

    img.onload = function () {
        imgW = img.width * scale;
        imgH = img.height * scale;
        if (imgW > CanvasXSize) { x = CanvasXSize - imgW; } // image larger than canvas
        if (imgW > CanvasXSize) { clearX = imgW; } // image larger than canvas
        else { clearX = CanvasXSize; }
        if (imgH > CanvasYSize) { clearY = imgH; } // image larger than canvas
        else { clearY = CanvasYSize; }
        //Get Canvas Element
        ctx = document.getElementById('canvas').getContext('2d');
        //Set Refresh Rate
        return setInterval(draw, speed);
    }

    function draw() {
        //Clear Canvas
        ctx.clearRect(0, 0, clearX, clearY);
        //If image is <= Canvas Size
        if (imgW <= CanvasXSize) {
            //reset, start from beginning
            if (x > (CanvasXSize)) { x = 0; }
            //draw aditional image
            if (x > (CanvasXSize - imgW)) { ctx.drawImage(img, x - CanvasXSize + 1, y, imgW, imgH); }
        }
            //If image is > Canvas Size
        else {
            //reset, start from beginning
            if (x > (CanvasXSize)) { x = CanvasXSize - imgW; }
            //draw aditional image
            if (x > (CanvasXSize - imgW)) { ctx.drawImage(img, x - imgW + 1, y, imgW, imgH); }
        }
        //draw image
        ctx.drawImage(img, x, y, imgW, imgH);
        //amount to move
        x += dx;
    }
</script>

<link href="css/main.css" rel="stylesheet" type="text/css" />
<script src="http://code.jquery.com/jquery-latest.min.js"></script>
<script src="js/pixastic.custom.js"></script>
<script src="js/script.js"></script>

<div class="container" style="margin-bottom:285px">
    <div class="slides">
        <img src="~/images/imageedit_11_3678298637.jpg" style='height: 800px; width: 800px; object-fit: contain;background-size: contain' ' />
        <img src="~/images/imageedit_3_4931344117.png" style='height: 800px; width: 800px; object-fit: contain;background-size: contain' ' />
        <img src="~/images/imageedit_5_6890471436.png" style='height: 800px; width: 800px; object-fit: contain;background-size: contain' ' />
        <img src="~/images/imageedit_7_9978923469.jpg" style='height: 800px; width: 800px; object-fit: contain ;background-size: contain' ' />
        <img src="~/images/imageedit_9_7879279680.jpg" style='height: 800px; width: 800px; object-fit: contain ;background-size: contain' />
    </div>
    <canvas id="slideshow" width="800" height="300"></canvas>
</div>

FinalProject/Views/Home/Contact.cshtml
@model IEnumerable<FinalProject.Models.Office>

@{
    ViewBag.Title = "Contact";
}
<h2>Company Offices</h2>

<p>Feel free to contact every one of our offices  - we want to know what you think!</p>

@using (Html.BeginForm())
{
    <p class="street-block">
        -----Street----- @Html.TextBox("Street")<br />
        ------City------ @Html.TextBox("city")<br />
        ---Manager--- @Html.TextBox("manager")<br />
        <input type="submit" value="Filter" class="btn btn-danger" />
        <input type="button" value="Show all" onclick="location.href='@Url.Action("Contact")'" class="btn btn-danger" />
    </p>
}
<div id="pageContent" style="min-width:600px">


    @if (User.Identity.Name.Equals("admin@gmail.com"))
    {
        @Html.Partial("_AdminContact", Model);
        <div id="map_canvas" class="offices-map" style="width: 800px; height: 500px; border:solid black 3px"></div>
    }
    else
    {
        @Html.Partial("_RegularContact", Model);
        <div id="map_canvas" class="col-xs-12 col-sm-12 col-md-8" style="height: 500px; border:solid black 3px"></div>
    }
</div>

<style>
    /* Always set the map height explicitly to define the size of the div
            * element that contains the map. */
    #map {
        height: 100%;
    }
    /* Optional: Makes the sample page fill the window. */
    html, body {
        margin: 0;
        padding: 0;
    }
</style>

<script>
            function AddMarker(map, Latitude, Longitude) {
                var latlng = new google.maps.LatLng(Latitude, Longitude);

                var markeroption = new google.maps.Marker({
                    position: latlng,
                    draggable: false,
                    map: map,
                    title: "Center"
                });
            }

            function initMap() {
                var latlng = new google.maps.LatLng(31.774120, 35.217933);

                var options = {
                    zoom: 7, center: latlng,
                    mapTypeId: google.maps.MapTypeId.TERRAIN
                };

                var map = new google.maps.Map(document.getElementById
                    ("map_canvas"), options);

                @foreach (var l in Model)
                {
                     @(string.Format("AddMarker(map, {0},{1});", l.Latitude, l.Longitude));
                }
                return map;
            };
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBz6T_-pt82oRbHIpMHvVQakDH6PzZ31C8&callback=initMap"
        async defer>
</script>

FinalProject/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="videocontainer">
    <video id="video" autoplay loop>
        <source src="~/Content/opening.mp4" type="video/mp4" />
    </video>
    <div class="overlay" style="font-size: 50px;">
        <h1 class="slogen" style="font-size:50px">Open Your Mind For Innovation </h1>
        <p class="slogen">Imagine how easy it will be to search your professionals</p>
        <button id="btn-businesses" onclick="location.href='@Url.Action("Index","Businesses")'"><div id="d-businesess">Start Searching</div></button>
    </div>
</div>

<style>
    video {
        width: 100%;
        height: auto;
    }

    .videocontainer {
        width: 100%;
        height: auto;
        position: relative;
    }

        .videocontainer video {
            width: 100%;
            height: auto;
            position: relative;
            z-index: 0;
        }

    .overlay {
        position: absolute;
        top: 10%;
        left: 10%;
        z-index: 1;
    }

    .slogen {
        font-size: xx-large;
        font-family: fantasy;
        -webkit-text-stroke: 1px black;
        color: yellow;
        text-shadow: 3px 3px 0 #000, -1px -1px 0 #000, 1px -1px 0 #000, -1px 1px 0 #000, 1px 1px 0 #000;
    }

    p.slogen {
        font-size: x-large;
    }

    #btn-businesses {
        outline: black solid 2.0px;
        background-color: gray;
        opacity: 0.2;
        padding: 6px 8px;
        border-radius: 3px;
        color: black;
        font-weight: bold;
        border: none;
        margin: 0;
    }

        #btn-businesses:hover {
            opacity: 0.9;
        }

    #d-businesess {
        font-family: helvetica, arial, sans-serif;
        font-size: 19pt;
        opacity: 1;
        color: yellow;
    }
</style>

FinalProject/Views/Home/_RegularContact.cshtml
@model IEnumerable<FinalProject.Models.Office>

<link rel="stylesheet" type="text/css" href="~/Content/regularContactStylesheet.css">
<aside>
    <div class="accordion" style="float:left; margin-bottom:185px; margin-right:30px">
        @foreach (var item in Model)
        {
            <div class="accordion-header"> @Html.DisplayFor(modelItem => item.City)</div>
            <div class="accordion-content"> @Html.DisplayFor(modelItem => item.HouseNumber) @Html.DisplayFor(modelItem => item.Street) <br /> @Html.DisplayFor(modelItem => item.Manager)</div>
        }
    </div>
</aside>
@if (Model.Count() == 0)
{
    <strong>No offices were Found</strong>
}
<script>
    // Clicking on the accordion header title...
    $(".accordion").on("click", ".accordion-header", function () {

        $(".accordion-header").removeClass("active");
        $(this).toggleClass("active").next().slideToggle();

        $('.accordion-content').not($(this).next()).slideUp();
    });
</script>

FinalProject/Views/Home/_adminContact.cshtml
@model IEnumerable<FinalProject.Models.Office>

<div class="table-responsive">
    <table class="table" style="margin-bottom:25px; background:#bcbec3 !important">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.OfficeID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Street)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HouseNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Latitude)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Longitude)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Manager)
            </th>
        </tr>


        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.OfficeID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.City)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Street)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HouseNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Latitude)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Longitude)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Manager)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", "Offices", new { id = item.OfficeID }, null) |
                    @Html.ActionLink("Details", "Details", "Offices", new { id = item.OfficeID }, null) |
                    @Html.ActionLink("Delete", "Delete", "Offices", new { id = item.OfficeID }, null)
                </td>
            </tr>

        }
    </table>
</div>