FinalProject/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FinalProject.Dal;
using FinalProject.Models;

namespace FinalProject.Controllers
{
    public class CategoriesController : Controller
    {
        private GeneralDbContext db = new GeneralDbContext();

        [Authorize]
        // GET: Categories
        public ActionResult Index()
        {
            return View(db.DBCategories.ToList());
        }

        [Authorize]
        // GET: Categories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.DBCategories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        [Authorize]
        // GET: Categories/Create
        public ActionResult Create()
        {
            return View();
        }

        [Authorize]
        // POST: Categories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CategoryID,CategoryName")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.DBCategories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);
        }

        [Authorize]
        // GET: Categories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.DBCategories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        [Authorize]
        // POST: Categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CategoryID,CategoryName")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        [Authorize]
        // GET: Categories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.DBCategories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        [Authorize]
        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.DBCategories.Find(id);
            db.DBCategories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FinalProject/Controllers/ChartController.cs
using FinalProject.Dal;
using FinalProject.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Helpers;
using System.Collections;

namespace FinalProject.Controllers
{
    public class ChartController : Controller
    {
        private GeneralDbContext db = new GeneralDbContext();

        [Authorize]
        // GET: Chart
        public ActionResult Index()
        {
            ReviewDateGroup objProductModel = new ReviewDateGroup();
            objProductModel.ReviewCountData = new ReviewCount();
            objProductModel.ReviewCountData = GetChartData();
            objProductModel.Title = "Months";
            objProductModel.CountTitle = "Review Count";
            
            return View(objProductModel);
        }

        [Authorize]
        public ReviewCount GetChartData()
        {
            try
            {
                ArrayList xValue = new ArrayList();
                ArrayList yValue = new ArrayList();
                var dBReview = db.DBReview.GroupBy(x => x.Date.Month).Select(x => new ReviewDateGroup { month = x.Key, ReviewCount = x.Count() });
                dBReview.ToList().ForEach(x => xValue.Add(x.month));
                dBReview.ToList().ForEach(x => yValue.Add(x.ReviewCount));

                var xV = xValue.Cast<Int32>().ToArray();
                var yV = yValue.Cast<Int32>().ToArray();
                ReviewCount objproduct = new ReviewCount();
                string strx = string.Join(",", xV);
                string stry = string.Join(",", yV);
                objproduct.Month = strx; //"1,2,3,4,5,6...";// string.Join(",", xV);//
                objproduct.Count = stry; //"2000,1000,3000,1500,2300,500"; //string.Join(",", yV);//
                return objproduct;
            }
            catch (Exception e)
            {
                return null;
            }
        }

        [Authorize]
        //Data for graph it shows how much Business in each category
        public JsonResult categoriesGraph()
        {

            List<Result> numOfBusinesses = new List<Result>();

            //Perform join to get all relevant categories
            var myQuery = from c in db.DBCategories
                        join b in db.DBBusiness on c.CategoryID equals b.CategoryID
                        select c;

            //Now we group it by category name and count it
            var myGroup = from t in myQuery
                          group t by t.CategoryName into cat
                          select new
                          {
                            CategoryName = cat.Key,
                            amount = cat.Count()
                          };
            //Make it in the right form for the view
            foreach (var item in myGroup)
            {
                Result numBusinesses = new Result();
                numBusinesses.State = item.CategoryName;
                numBusinesses.freq = item.amount;
                numOfBusinesses.Add(numBusinesses);
            }

            return Json(numOfBusinesses, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        public JsonResult topFiveGraph()
        {

            List<Result> numOfReviews = new List<Result>();

            /*Join by BusinessID*/
            var myQuery = from b in db.DBBusiness
                          join r in db.DBReview on b.BusinessID equals r.BusinessID
                        select b;


            /*now we group it for the graph*/
            var myGroup = from t in myQuery
                        group t by t.BusinessName into cat
                        select new
                        {
                            cName = cat.Key,
                            Num = cat.Count()
                        };

            var myQuery2 = (from y in @myGroup
                         where y.Num >= 1
                         orderby y.Num descending
                         select y).Take(5);

            foreach (var item in myQuery2)
            {
                Result numReviews = new Result();
                numReviews.State = item.cName;
                numReviews.freq = item.Num;
                numOfReviews.Add(numReviews);
            }

            return Json(numOfReviews, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        // GET: Chart/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        [Authorize]
        // GET: Chart/Create
        public ActionResult Create()
        {
            return View();
        }

        [Authorize]
        // POST: Chart/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [Authorize]
        // GET: Chart/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        [Authorize]
        // POST: Chart/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [Authorize]
        // GET: Chart/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        [Authorize]
        // POST: Chart/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

FinalProject/Controllers/OfficesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FinalProject.Dal;
using FinalProject.Models;
using System.Data.SqlClient;
using System.Configuration;

namespace FinalProject.Controllers
{
    public class OfficesController : Controller
    {
        private GeneralDbContext db = new GeneralDbContext();

        // GET: Offices
        public ActionResult Index(string Street, string city, string manager)
        {
            var Offices = from o in db.DBOffice select o;
            if (!String.IsNullOrEmpty(Street))
            {
                Offices = Offices.Where(s => s.Street.ToLower().Contains(Street.ToLower()));
            }
            if (!String.IsNullOrEmpty(city))
            {
                Offices = Offices.Where(s => s.City.ToLower().Contains(city.ToLower()));
            }
            if (!String.IsNullOrEmpty(manager))
            {
                Offices = Offices.Where(s => s.Manager.ToLower().Contains(manager.ToLower()));
            }

            return View(Offices);
        }

        // GET: Offices/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Office office = db.DBOffice.Find(id);
            if (office == null)
            {
                return HttpNotFound();
            }
            return View(office);
        }

        // GET: Offices/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Offices/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OfficeID,BusinessName,City,Street,HouseNumber,Latitude,Longitude,Owner,Manager")] Office office)
        {
            if (ModelState.IsValid)
            {
                db.DBOffice.Add(office);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(office);
        }

        // GET: Offices/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Office office = db.DBOffice.Find(id);
            if (office == null)
            {
                return HttpNotFound();
            }
            return View(office);
        }

        // POST: Offices/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OfficeID,BusinessName,City,Street,HouseNumber,Latitude,Longitude,Owner,Manager")] Office office)
        {
            if (ModelState.IsValid)
            {
                db.Entry(office).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(office);
        }

        // GET: Offices/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Office office = db.DBOffice.Find(id);
            if (office == null)
            {
                return HttpNotFound();
            }
            return View(office);
        }

        // POST: Offices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Office office = db.DBOffice.Find(id);
            db.DBOffice.Remove(office);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FinalProject/Views/Chart/Index.cshtml
@model FinalProject.ViewModel.ReviewDateGroup
@{
    ViewBag.Title = "Index";
}
<link rel="stylesheet" type="text/css" href="~/Content/AdminPage.css">
<div style="text-align:center;margin-bottom:10px">
    <input class="btn" type="button" value="Company Offices" onclick="location.href='@Url.Action("Index","Offices")'" />
    <input class="btn" type="button" value="Reviews" onclick="location.href='@Url.Action("Index","Reviews")'" />
    <input class="btn" type="button" value="Businesses" onclick="location.href='@Url.Action("Index","Businesses")'" />
    <input class="btn" type="button" value="Businesses Categories" onclick="location.href='@Url.Action("Index","Categories")'" />
    <br />
    <div class="row">
        <div class="col-md-1 offset-md-2">@Html.Partial("_ReviewsPerMonth", Model)</div>
    </div>
    <div class="row">
        <div class="col-md-2 offset-md-2">@Html.Partial("_BusinessesPerCategory", Model)</div>
    </div>
    <div class="row">
        <div class="col-md-2 offset-md-2">@Html.Partial("_topFive", Model)</div>
    </div>
</div>

FinalProject/Views/Chart/_BusinessesPerCategory.cshtml
<link rel="stylesheet" type="text/css" href="~/Content/Site.css" media="all" />
<link rel="stylesheet" type="text/css" href="~/Content/BusinessesPerCategoryStylesheet.css" />

<div id='dashboard'></div>

<script src="http://d3js.org/d3.v3.min.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script type="text/javascript">
        function dashboard(id, jData) {
            var barColor = '#3366cc';

            // compute total for each state.
            jData.forEach(function (d) { d.total = d.freq; });

            // function to handle histogram.
            function histoGram(jD) {
                var hG = {}, hGDim = { t: 60, r: 0, b: 30, l: 0 };
                hGDim.w = 500 - hGDim.l - hGDim.r,
                hGDim.h = 300 - hGDim.t - hGDim.b;

                //create svg for histogram.
                var hGsvg = d3.select(id).append("svg")
                    .attr("width", hGDim.w + hGDim.l + hGDim.r)
                    .attr("height", hGDim.h + hGDim.t + hGDim.b).append("g")
                    .attr("transform", "translate(" + hGDim.l + "," + hGDim.t + ")");

                // create function for x-axis mapping.
                var x = d3.scale.ordinal().rangeRoundBands([0, hGDim.w], 0.1)
                        .domain(jD.map(function (d) { return d[0]; }));

                // Add x-axis to the histogram svg.
                hGsvg.append("g").attr("class", "x axis")
                    .attr("transform", "translate(0," + hGDim.h + ")")
                    .call(d3.svg.axis().scale(x).orient("bottom"));

                // Create function for y-axis map.
                var y = d3.scale.linear().range([hGDim.h, 0])
                        .domain([0, d3.max(jD, function (d) { return d[1]; })]);

                // Create bars for histogram to contain rectangles and freq labels.
                var bars = hGsvg.selectAll(".bar").data(jD).enter()
                        .append("g").attr("class", "bar");

                //create the rectangles.
                bars.append("rect")
                    .attr("x", function (d) { return x(d[0]); })
                    .attr("y", function (d) { return y(d[1]); })
                    .attr("width", x.rangeBand())
                    .attr("height", function (d) { return hGDim.h - y(d[1]); })
                    .attr('fill', barColor)
                    .on("mouseover", mouseover)// mouseover is defined below.
                    .on("mouseout", mouseout);// mouseout is defined below.

                //Create the frequency labels above the rectangles.
                bars.append("text").text(function (d) { return d3.format(",")(d[1]) })
                    .attr("x", function (d) { return x(d[0]) + x.rangeBand() / 2; })
                    .attr("y", function (d) { return y(d[1]) - 5; })
                    .attr("text-anchor", "middle");

                function mouseover(d) // utility function to be called on mouseover.
                {
                    // filter for selected state.
                    var st = jData.filter(function (s) { return s.State == d[0]; })[0],
                        nD = d3.keys(st.freq).map(function (s) { return { type: s, freq: st.freq[s] }; });
                }

                function mouseout(d) { }    // utility function to be called on mouseout.

                // create function to update the bars. This will be used by pie-chart.
                hG.update = function (nD, color) {
                    // update the domain of the y-axis map to reflect change in frequencies.
                    y.domain([0, d3.max(nD, function (d) { return d[1]; })]);

                    // Attach the new data to the bars.
                    var bars = hGsvg.selectAll(".bar").data(nD);

                    // transition the height and color of rectangles.
                    bars.select("rect").transition().duration(500)
                        .attr("y", function (d) { return y(d[1]); })
                        .attr("height", function (d) { return hGDim.h - y(d[1]); })
                        .attr("fill", color);

                    // transition the frequency labels location and change value.
                    bars.select("text").transition().duration(500)
                        .text(function (d) { return d3.format(",")(d[1]) })
                        .attr("y", function (d) { return y(d[1]) - 5; });
                }
                return hG;
            }


            // calculate total frequency by state for all segment.
            var sF = jData.map(function (d) { return [d.State, d.total]; });

            var hG = histoGram(sF); // create the histogram.

        }
        $.getJSON('/Chart/categoriesGraph', function (data) {
            dashboard('#dashboard', data);
        });
</script>

FinalProject/Views/Chart/_ReviewsPerMonth.cshtml
@model FinalProject.ViewModel.ReviewDateGroup

<div id="partialPlaceHolder" style="align-content:center"></div>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">

    google.load("visualization", "1", { packages: ["corechart"] });
    google.setOnLoadCallback(drawChart);

    function drawChart() {
        // Create and populate the data table.
        var month = [@Model.ReviewCountData.Month];
        var count = [ @Model.ReviewCountData.Count];


        var data = new google.visualization.DataTable();
        data.addColumn('string', '@Model.Title');
        data.addColumn('number', '@Model.CountTitle');
        var _Month = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
        for (i = 0; i < month.length; i++) {
            data.addRow([_Month[month[i] - 1].toString(), count[i]]);
        }
        var options = {
            title: 'Annual Review Count',
            hAxis: { title: '@Model.Title', titleTextStyle: { color: 'red' } }
        };

        var chart = new google.visualization.ColumnChart(document.getElementById('chart_div'));
        chart.draw(data, options);
    }

</script>
<br />
<div id="chart_div" style="width:600px; height: 300px;"></div>

FinalProject/Views/Chart/_topFive.cshtml
<link rel="stylesheet" type="text/css" href="~/Content/Site.css" media="all" />
<link rel="stylesheet" type="text/css" href="~/Content/BusinessesPerCategoryStylesheet.css" />

<div id='dashboard2'></div>

<script src="http://d3js.org/d3.v3.min.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script type="text/javascript">
    function dashboard(id, jData) {
        var barColor = '#3366cc';

        // compute total for each state.
        jData.forEach(function (d) { d.total = d.freq; });

        // function to handle histogram.
        function histoGram(jD) {
            var hG = {}, hGDim = { t: 60, r: 0, b: 30, l: 0 };
            hGDim.w = 500 - hGDim.l - hGDim.r,
            hGDim.h = 300 - hGDim.t - hGDim.b;

            //create svg for histogram.
            var hGsvg = d3.select(id).append("svg")
                .attr("width", hGDim.w + hGDim.l + hGDim.r)
                .attr("height", hGDim.h + hGDim.t + hGDim.b).append("g")
                .attr("transform", "translate(" + hGDim.l + "," + hGDim.t + ")");

            // create function for x-axis mapping.
            var x = d3.scale.ordinal().rangeRoundBands([0, hGDim.w], 0.1)
                    .domain(jD.map(function (d) { return d[0]; }));

            // Add x-axis to the histogram svg.
            hGsvg.append("g").attr("class", "x axis")
                .attr("transform", "translate(0," + hGDim.h + ")")
                .call(d3.svg.axis().scale(x).orient("bottom"));

            // Create function for y-axis map.
            var y = d3.scale.linear().range([hGDim.h, 0])
                    .domain([0, d3.max(jD, function (d) { return d[1]; })]);

            // Create bars for histogram to contain rectangles and freq labels.
            var bars = hGsvg.selectAll(".bar").data(jD).enter()
                    .append("g").attr("class", "bar");

            //create the rectangles.
            bars.append("rect")
                .attr("x", function (d) { return x(d[0]); })
                .attr("y", function (d) { return y(d[1]); })
                .attr("width", x.rangeBand())
                .attr("height", function (d) { return hGDim.h - y(d[1]); })
                .attr('fill', barColor)
                .on("mouseover", mouseover)// mouseover is defined below.
                .on("mouseout", mouseout);// mouseout is defined below.

            //Create the frequency labels above the rectangles.
            bars.append("text").text(function (d) { return d3.format(",")(d[1]) })
                .attr("x", function (d) { return x(d[0]) + x.rangeBand() / 2; })
                .attr("y", function (d) { return y(d[1]) - 5; })
                .attr("text-anchor", "middle");

            function mouseover(d) // utility function to be called on mouseover.
            {
                // filter for selected state.
                var st = jData.filter(function (s) { return s.State == d[0]; })[0],
                    nD = d3.keys(st.freq).map(function (s) { return { type: s, freq: st.freq[s] }; });
            }

            function mouseout(d) { }    // utility function to be called on mouseout.

            // create function to update the bars. This will be used by pie-chart.
            hG.update = function (nD, color) {
                // update the domain of the y-axis map to reflect change in frequencies.
                y.domain([0, d3.max(nD, function (d) { return d[1]; })]);

                // Attach the new data to the bars.
                var bars = hGsvg.selectAll(".bar").data(nD);

                // transition the height and color of rectangles.
                bars.select("rect").transition().duration(500)
                    .attr("y", function (d) { return y(d[1]); })
                    .attr("height", function (d) { return hGDim.h - y(d[1]); })
                    .attr("fill", color);

                // transition the frequency labels location and change value.
                bars.select("text").transition().duration(500)
                    .text(function (d) { return d3.format(",")(d[1]) })
                    .attr("y", function (d) { return y(d[1]) - 5; });
            }
            return hG;
        }


        // calculate total frequency by state for all segment.
        var sF = jData.map(function (d) { return [d.State, d.total]; });

        var hG = histoGram(sF); // create the histogram.

    }

    $.getJSON('/Chart/topFiveGraph', function (data) {
        dashboard('#dashboard2', data);
    });


</script>